imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services_ginco.yml }
    - { resource: services_configurator.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%", 'en'] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
    default_locale:  "%locale%"
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_path: "%basepath%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: app.exception_controller:showAction
    globals: 
      configurationManager : '@ginco.configuration_manager'
      anonymous: '@app.anonymous_user'

    # Use Boostrap forms - horizontal and overriden 4 + 4 columns
    form_themes:
        - form.html.twig
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: website
        connections:
            website:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                server_version: "%database_version%"
                charset:  UTF8
                mapping_types:
                    geometry: string
                    _text: string
                schema_filter: /website\./i
                logging: false
                profiling: false
            mapping:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                server_version: "%database_version%"
                charset:  UTF8
                mapping_types:
                    geometry: string
                    _text: string
                schema_filter: /mapping\./i
                logging: false
                profiling: false
            metadata:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                server_version: "%database_version%"
                charset:  UTF8
                mapping_types:
                    geometry: string
                    _text: string
                schema_filter: /metadata\./i
                logging: false
                profiling: false
            raw_data:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                server_version: "%database_version%"
                charset:  UTF8
                mapping_types:
                    geometry: string
                    _text: string
                schema_filter: /raw_data\./i
                logging: false
                profiling: false

    orm:
        auto_generate_proxy_classes: "FILE_NOT_EXISTS"
        default_entity_manager: website
        entity_managers:
            metadata_work:
                mappings:
                    IgnOGAMConfigurateurBundle: ~
            website:
                 connection: website
                 mappings:
                     IgnGincoBundle:
                        dir: Entity/Website
            mapping:
                 connection: mapping
                 mappings:
                    IgnGincoBundle:
                        dir: Entity/Mapping
            metadata:
                 connection: metadata
                 mappings:
                    IgnGincoBundle:
                     dir: Entity/Metadata
            raw_data:
                 connection: raw_data
                 mappings:
                     IgnGincoBundle:
                        dir: Entity/RawData


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# breadcrumb configuration
white_october_breadcrumbs:
    separator: ''

fos_js_routing:
    routes_to_expose: [configurateur_table_add_fields, configurateur_file_add_fields, configurateur_table_update_fields, configurateur_file_update_fields, configurateur_table_edit_save, configurateur_file_field_mask_save, configurateur_table_change_mandatory_state, configurateur_file_change_mandatory_state, configurateur_dataset_import_update_file_order]

ign_ogam_configurateur:
    database_name: "%database_name%"
    
# Rabbit_mq configuration
old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false
            # requires php-amqplib v2.4.1+
            heartbeat: 0

    producers:
        ginco_generic:
            connection:       default
            exchange_options: {name: 'ginco_%instance_name%_generic', type: direct}
    consumers:
        ginco_generic:
            connection:       default
            exchange_options: {name: 'ginco_%instance_name%_generic', type: direct}
            queue_options: {name: 'ginco_%instance_name%_generic'}
            callback: generic_consumer_service
            graceful_max_execution:
                timeout: 3600 # 1 hour
                exit_code: 10 # default is 0

# FOS CKEditor
fos_ck_editor:
    base_path: "vendor/ckeditor"
    js_path: "vendor/ckeditor/ckeditor.js"
    default_config: my_config
    configs:
        my_config:
            toolbar: standard
            removeButtons: ''
