# @ annotation for the parent bundle creates problem with routes when adding controller in child bundle
ign_ogam:
    resource: "../../src/Ign/Bundle/OGAMBundle/Controller/"
    type:     annotation
    prefix:   /

ign_ginco:
    resource: "@IgnGincoBundle/Controller/"
    type:     annotation
    prefix:   /

ign_ogam_configurateur:
    resource: "../../src/Ign/Bundle/OGAMConfigurateurBundle/Controller/"
    type:     annotation
    prefix:   /configurator

ign_ginco_configurateur:
    resource: "@IgnGincoConfigurateurBundle/Controller/"
    type:     annotation
    prefix:   /configurator

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"