# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        website_base:
            entity:
                class: Ign\Bundle\OGAMBundle\Entity\Website\User
                property: login
                manager_name: website

    encoders:
        Ign\Bundle\OGAMBundle\Entity\Website\User:
            id: ogam.challenge_response_encoder

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_validatelogin
            logout:
                path:   user_logout
                target: /
            entry_point: OGAMBundle.login_entry_point
    access_control:
        - { path: ^/user/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usermanagement/, allow_if: "user and is_authenticated() and user.isAllowed('MANAGE_USERS')"}
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/dataedition/, allow_if: "user and is_authenticated() and user.isAllowed('DATA_EDITION')"}
        - { path: ^/query/, allow_if: "user and is_authenticated() and user.isAllowed('DATA_QUERY', request.getSession().get('_schema', 'RAW_DATA'))"}
        - { path: ^/map/, allow_if: "user and is_authenticated() and user.isAllowed('DATA_QUERY', request.getSession().get('_schema', 'RAW_DATA'))"}
        - { path: ^/integration/, allow_if: "user and is_authenticated() and user.isAllowed('DATA_INTEGRATION')"}
        - { path: ^/proxy/, allow_if: "user and is_authenticated() and user.isAllowed('DATA_INTEGRATION')"}
        - { path: ^/harmonization/, allow_if: "user and is_authenticated() and user.isAllowed('DATA_INTEGRATION')"}
        - { path: ^/checkconf/, allow_if: "user and is_authenticated() and user.isAllowed('CHECK_CONF')"}
        - { path: ^/configuration/, allow_if: "user and is_authenticated() and user.isAllowed('CONFIGURE_WEBSITE_PARAMETERS')"}
        - { path: ^/configurator/, allow_if: "user and is_authenticated() and user.isAllowed('CONFIGURE_METAMODEL')"}

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
