# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        website_base:
            entity:
                class: Ign\Bundle\GincoBundle\Entity\Website\User
                property: login
                manager_name: website

    encoders:
        Ign\Bundle\GincoBundle\Entity\Website\User:
            id: ginco.challenge_response_encoder

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            guard:
              authenticators:
                - ginco.cas_authenticator
            logout:
              path:   app_logout
              target: /

    access_control:
        - { path: ^/user/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usermanagement/search-providers, allow_if: "user and is_authenticated() and (user.isAllowed('MANAGE_OWN_PROVIDER') or user.isAllowed('MANAGE_USERS'))"}
        - { path: ^/usermanagement/, allow_if: "user and is_authenticated() and user.isAllowed('MANAGE_USERS')"}
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/dataedition/, roles: "EDIT_DATA"}
        - { path: ^/query/csv-export, allow_if: "user and is_authenticated() and user.isAllowed('EXPORT_RAW_DATA')"}
        - { path: ^/query/, roles: "IS_AUTHENTICATED_ANONYMOUSLY"}
        - { path: ^/map/, roles: "IS_AUTHENTICATED_ANONYMOUSLY"}
        - { path: ^/integration/, allow_if: "user and is_authenticated() and user.isAllowed('DATA_INTEGRATION')"}
        - { path: ^/geo-association/update-jdd, allow_if: "user and is_authenticated() and user.isAllowed('DATA_INTEGRATION')"}
        - { path: ^/geo-association/update-entity, allow_if: "user and is_authenticated() and user.isAllowed('DATA_INTEGRATION')"}
        - { path: ^/jdd/, allow_if: "user and is_authenticated() and user.isAllowed('DATA_INTEGRATION')"}
        - { path: ^/submission/download-report, allow_if: "user and is_authenticated() and user.isAllowed('DATA_INTEGRATION')"}
        - { path: ^/dee/, roles: "IS_AUTHENTICATED_FULLY"}
        - { path: ^/proxy/, allow_if: "user and is_authenticated() and user.isAllowed('DATA_INTEGRATION')"}
        - { path: ^/configuration/, allow_if: "user and is_authenticated() and user.isAllowed('CONFIGURE_WEBSITE_PARAMETERS')"}
        - { path: ^/configurator/, allow_if: "user and is_authenticated() and user.isAllowed('CONFIGURE_METAMODEL')"}
        - { path: ^/taxref-migration, allow_if: "user and is_authenticated() and user.isAllowed('CONFIGURE_WEBSITE_PARAMETERS')"}

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
